# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b7bc873bf103d070a7a9ed35183a8e68eb589a33bee8af9174f7be101db40ef121e77074a61ea13471d72a335280881363c522d07dc0939e1018577f814c0e8

test:
  secret_key_base: 2a95bb32623e58410fd7da4e301ac34cba3ad863041ab344350ca12ed4ba42ca7d4343e529109af7eb6448eeb404e7e544222f84e36d6a1d1e8e537251d3d417

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
